### PR TITLE
Add SHACL tests

### PR DESCRIPTION
**Pull request by schivmeister**
- There must exist at least one NodeShape
- There should not be additional types declared on a NodeShape
- By extension, there should not be types beyond OWL and SHACL
- There should be a severity declared in any shape

SEMIC rules: DSC-R1, DSC-R4 (partial), DSC-R5

### CODE REVIEW

**Review by csnyulas — APPROVED** [review]
Looks fine to me. Not 100% what the change to the SHACL shape does, but I assume it is OK, and was tested and works.
Should be totally fine to merge. Bugs can be fixed later, if any is discovered. Nothing is obviously wrong.

**Comment by schivmeister** [comment]
@csnyulas could you clarify `what the change to the SHACL shape does` - which "change" are you referring to?

**Comment by csnyulas** [comment]
Sorry for not being specific enough earlier @schivmeister . I meant this change:
https://github.com/meaningfy-ws/semic-styleguide-rdf-validator/pull/4/commits/2b4eeaa77a9bdcb8c85510ea8d68289ab3ce14c5#diff-ec0159ef45ab1f653358e9e861d044813a4f887df1c9c4829b71a9a737e6177f
but of course there were many more changes to many other shapes, so you couldn't have guessed.
I don't need an explanation, really, just wanted to note that not everything I could understand 100%. However, overall nothing jumps to my eyes as being wrong.

**Comment by schivmeister** [comment]
Got it @csnyulas, I should at least try to clarify again because I was trying very hard to find the right words in the commit message. But in general it refers to the situation where either the NodeShape or _the related_ PropertyShape should have the severity declared (captures cases where the NodeShape is standalone, usually when there is a "focus node" (a specific instance to validate without specifying a property restriction), although this case is not represented by ePO)

**Pull request merged**
